trigger:
- master

pool:
  name: bhargav

variables:
  # Define the JDK version
  javaVersion: '8'

jobs:
- job: BuildAndPush
  displayName: 'Build and Push to Docker Hub'
  steps:

  - task: UseJavaVersion@1
    inputs:
      versionSpec: '$(javaVersion)'
      addToPath: true

  - script: |
      echo '##vso[task.prependpath]/usr/lib/jvm/zulu-8-amd64/bin/'
    displayName: 'Add Java to PATH'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      jdkArchitectureOption: 'x64'
      goals: 'clean package'

  - task: Docker@2
    inputs:
      containerRegistry: 'Docker Hub Connection'
      repository: '<your-dockerhub-username>/<your-dockerhub-repository>'
      command: 'buildAndPush'
      Dockerfile: '<path-to-dockerfile>'
      tags: |
        $(Build.SourceBranchName)-$(Build.BuildId)
        latest

# Add additional steps as needed for deployment or other tasks.
